  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_arm_base
    pid: {p: 10, i: 0.0, d: 3}
    
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_1_to_arm_base
    pid: {p: 10, i: 0.0, d: 2}
    
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_2_to_arm_1
    pid: {p: 10, i: 2, d: 2}
    
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_3_to_arm_2
    pid: {p: 10, i: 2, d: 1.5}


